sudo: required
services:
  -docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - export 
  #CLOUDSDK_CORE_DISABLE_PROMPTS=1; 
  curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  #- gcloud config set project multi-k8s-340516
  #- gcloud config set compute/zone asia-east1-a
  #- gcloud container clusters get-credentials multi-cluser
  - gcloud container clusters get-credentials multi-cluser --zone=asia-east1-a --project=multi-k8s-340516
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t viideguzman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true viideguzman/react-test npm install react-scripts --save

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch:  complex-kubernetes