sudo: required
services:
  - docker

before_install:
  - docker build -t dockertravis2/docker-react -f ./client/Dockerfile.dev ./client

script:
  -  docker run -e CI=true dockertravis2/docker-react npm install react-scripts --save

after_success:
  - docker build -t dockertravis2/multi-client ./client
  - docker build -t dockertravis2/multi-nginx ./nginx
  - docker build -t dockertravis2/multi-server ./server
  - docker build -t dockertravis2/multi-worker ./worker

#Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push images to docker hub
  - docker push dockertravis2/multi-client
  - docker push dockertravis2/multi-nginx
  - docker push dockertravis2/multi-server
  - docker push dockertravis2/multi-worker
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-us-east-2-262276837591"
#  bucket_path: "docker-react-app"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY